const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_MESSAGE = "NEW_MESSAGE"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

export {
    REFETCH_CHATS,
    NEW_MESSAGE,
    NEW_MESSAGE_ALERT,
    NEW_REQUEST
}